---
- hosts: ansible_provision
  gather_facts: no
  connection: local
  vars:
    ansible_mgmt_user: "ansible"
    ansible_mgmt_user_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfPIOm6TSo7pffbQzWCp9NILUZTPURMotgyfILXzbqb5xmaYGPN/CnDkbTD6EXoHklqhnT7eLVHjg2F93GtkNf8k5cy1UpPBkJ9YUGK9bJdaVN/VtFhU+lAUcXVu/DfPBfCywGDlznmlJItwCHY39vB8z+SqK+OEDkL1hARSmaG4ulhdymJ8wg8U5jOHmnaVi0eGXUrjVYK67jahru/7r90Vpt+3wWLzzHAH9hqI+IJImsFUxaNQuunLhmtGVg991Tz8tqwQjIJVaCdOcKN7KWhN+rXZPqYfX8OEe6S+BxPSW+13IBu6X61la96MjGGEm+XgsrkSLqBk7J75jlycwN martin@timeMachine"
  roles:
    - mikrotik-initialize

  vars_prompt:
  - name: ssh_port
    prompt: "SSH Port"
    private: no

  - name: ssh_login
    prompt: "Login"
    private: no

  - name: ssh_passwd
    prompt: "Password"
    private: yes
